### ISSUE TITLE
alpha2で指定した壁紙が表示されない．

### ISSUE THREAD

**Issue by rkarsnk** [PlasmaLinux/PLDE_Livebuild#11]
LiveImageを起動する環境によって，指定した壁紙が表示されない．

**Comment by rkarsnk** [comment]
VirtualBox，VMWare Workstation Playerでは，以下のプロパティに設定する必要がある．
```
/backdrop/screen0/monitorVirtual1/workspace0/last-image 
```

**Comment by Plasma-Linux** [comment]
設定方法は調査中ですか?

**Comment by rkarsnk** [comment]
@Plasma-Linux xfconf-query コマンドを使えば設定できるが，全ての動作環境をサポートするのは簡単ではない．

**Comment by Plasma-Linux** [comment]
なるほど。

**Comment by aruelu** [comment]
以下で壁紙の変更は可能だが呼び出し権限とタイミングで変更に失敗する。
```
#!/bin/bash


(
RUNFILE_DIR=~/.config/plasmalinux
RUNFILE="$RUNFILE_DIR"/.set_plasmalinux_backgrounds_run
DEFAULT_BACKGROUNDS=/usr/share/backgrounds/plasma_dark.png
GETMONITOR=`xfconf-query -c xfce4-desktop -lv | grep last-image | grep -v "$DEFAULT_BACKGROUNDS"`

if [ "$XDG_SESSION_DESKTOP" != "xfce" -o "$DESKTOP_SESSION" != "xfce"  ]
then
    exit 1
fi

if [ -e "$RUNFILE" ]
then
    exit 2
fi

for v in "${GETMONITOR[@]}"
do
    SETMONITOR=`echo "$v" | cut -f 1 -d" "`
#    echo $SETMONITOR
    if [ "$SETMONITOR" != "" ]
    then
        xfconf-query -c xfce4-desktop -p ${SETMONITOR} -s ${DEFAULT_BACKGROUNDS}
    fi
done

if [ ! -e "$RUNFILE_DIR" ]
then
    mkdir "$RUNFILE_DIR"
fi
touch "$RUNFILE"
) &> /tmp/test$$.txt
```

**Comment by rkarsnk** [comment]
サブシェルにしてるのはなんでですか？
```
(
...
) &> /tmp/test$$.txt

**Comment by aruelu** [comment]
ログを出すだけです。
呼び出し元で指定すれば、サブシェルにする必要ないです。

**Comment by rkarsnk** [comment]
このシェルスクリプトをベースにして，LightDMのsession-setup-scriptから呼び出すようにしてテストしてみます．

**Comment by aruelu** [comment]
有難う御座います。
私には良い対策が思いつかないので助かります。
以下、試した結果です。
root権限による実行では変更に失敗。
.bashrcから呼び出しでは、変更は成功するが、Terminalの起動が必要。
profile.d、rc5.dからの呼び出しでは失敗。

**Comment by aruelu** [comment]
systemdからの呼び出しでも失敗です。

**Comment by rkarsnk** [comment]
情報ありがとう，参考にします．

**Comment by aruelu** [comment]
環境変数のチェックを少し変更しないと、このままだと、チェック対象の両方がxfceでないと処理中断してしまう・・・。

**Comment by rkarsnk** [comment]
> 環境変数のチェックを少し変更しないと、このままだと、チェック対象の両方がxfceでないと処理中断してしまう・・・。

その辺も含めて，テストしながらスクリプト作成します．

**Comment by aruelu** [comment]
有り難うございます。
こんな感じでいいかと思います。

if [ "$XDG_SESSION_DESKTOP" = "xfce" -o "$DESKTOP_SESSION" = "xfce"  ]
then
    :
else
    exit 1
fi

**Comment by rkarsnk** [comment]
@aruelu 
ここに書いてあるスクリプトを参考にしました．
https://forum.xfce.org/viewtopic.php?id=14986

私の環境では動作確認できました．

実機上にコピーして試すこと可能ですか?

Live環境を起動後
```
sudo apt update
sudo apt install ssh
```
として，ssh-serverをインストールし，別のPCからscpで下のシェルスクリプトをコピーすれば，Live環境でも動作確認できると思います．

```
#!/bin/bash

DEFAULT_BACKGROUNDS=/usr/share/backgrounds/plasma_dark.png
RUNFILE_DIR=~/.config/plasmalinux
RUNFILE="$RUNFILE_DIR"/.plasmalinux_backgrounds.run

# exit if the script has been run before
[[ -f $RUNFILE ]] && exit 1


# get list of screens/monitors in an array (in case more that one monitor)
mapfile -t SCREENS < <(xfconf-query -c xfce4-desktop -lv | grep last-image | awk -F'/' '{print $3}')
mapfile -t MONITORS < <(xfconf-query -c xfce4-desktop -lv | grep last-image | awk -F'/' '{print $4}')

# cycle through array creating entries
for (( x=0; x <= ${#SCREENS[@]}; x++ ))
do
   xfconf-query -c xfce4-desktop -p /backdrop/${SCREENS[x]}/${MONITORS[x]}/workspace0/last-image -s ${DEFAULT_BACKGROUNDS}
done

# leave marker that script has been run
mkdir "${RUNFILE_DIR}"
touch $RUNFILE

exit 0
```

**Comment by aruelu** [comment]
試してみます。
autostartからの起動で上手くいくかは、やはり、isoファイル作らないと無理ですかね？
liveの/etc/skelにdesktopファイル入れれば、インストール後に反映できますか？

**Comment by rkarsnk** [comment]
Live環境でもadduserコマンドを使えば，新規ユーザが作成できます．
以下の手順で，確認できると思います
1. /etc/skelにdesktopファイルを配置したあと，adduserで新規ユーザ作成．
2. ログアウトする
3. 作成したユーザでログイン

**Comment by aruelu** [comment]
有り難うございます。
試してみます。

**Comment by aruelu** [comment]
adduserでユーザー追加後、一度目のログインでは変更失敗。
RUNFILEを削除した後に再度ログインで変更成功。

タイミングで失敗してるみたいですね。

**Comment by rkarsnk** [comment]
adduser した後に、sudo su- でrootユーザになって、作成したユーザのRUNFILEが作成されているか確認してみてください．

**Comment by aruelu** [comment]
RUNFILEは作成されてないです。

**Comment by rkarsnk** [comment]
一度目のログインをした直後は、RUNFILEは作成されている？

**Comment by aruelu** [comment]
作成されてます。

**Comment by rkarsnk** [comment]
RUNFILEが作成されているということは、最初のログインでautorunが実行されていることになるなぁ．
`xfconf-query -c xfce4-desktop -p /backdrop/${SCREENS[x]}/${MONITORS[x]}/workspace0/last-image -s ${DEFAULT_BACKGROUNDS}` のエラーメッセージを/tmp以下のファイルに書き出して確認できる？

**Comment by aruelu** [comment]
少しタイミングが変になりますが、スクリプトの頭でsleep 10 入れたら初回ログイン時に変更に成功しました。

**Comment by rkarsnk** [comment]
xfconfが起動する前にxfconf-queryを実行している可能性があるのか．
`sleep 1`だとどうだろ？
壁紙を別のものに変更したあと、RUNFILE削除して、再ログインしてみて？

**Comment by aruelu** [comment]
sleep 1で成功しました。
初回ログインにするために、新規ユーザー作成して確認しました。

**Comment by rkarsnk** [comment]
じゃ、sleep 1 追加した版でコミットおねがいします．

あと、6行目付近のexit 1は0に変更しておいてください．
```diff
# exit if the script has been run before
-[[ -f $RUNFILE ]] && exit 1
+[[ -f $RUNFILE ]] && exit 0
```
