### ISSUE TITLE
os-releaseをPlasmaLinuxのものにする

### ISSUE THREAD

**Issue by rkarsnk** [PlasmaLinux/PLDE_Livebuild#15]
os-releaseがDebianのまま．

**Comment by Plasma-Linux** [comment]
確かoYoにいたとき勝手に変えられたりしたからrc.localで何とかなるかなーって思ってます。(リポジトリもそう)

**Comment by rkarsnk** [comment]
@Plasma-Linux rc.localはセキュアなやり方じゃないから，systemdの仕組みを使いたいと思っている．

**Comment by aruelu** [comment]
BuildISO/resources/rootfs/に下記を入れておくことにより、ビルド後のISOファイルでインストールした環境でファイルが置き換わっていることを確認しました。
また、isb_release -a(lsb-releaseパッケージをインストール）にて反映されていることも確認しました。
etc/issue
etc/issue.net
lib/os-release（etc/os-releaseのシンボリックリンクのリンク先）

この３ファイルの変更だけで良ければ、ファイルを用意しておけば大丈夫そうです。

**Comment by rkarsnk** [comment]
レビューしたいので，PR出して貰えると助かります．

**Comment by aruelu** [comment]
それぞれの内容はこんな感じでしょうか？
VERSION_CODENAMEはtestingにしてますが何か指定あれば教えて下さい。

etc/issue
```
Plasma GNU/Linux alpha2 \n \l
```

etc/issue.net
```
Plasma GNU/Linux alpha2↲
```

lib/os-release（etc/os-releaseのシンボリックリンクのリンク先）
```
PRETTY_NAME="Plasma GNU/Linux alpha2 (testing)"
NAME="Plasma GNU/Linux"
VERSION_ID="alpha2"
VERSION="alpha2 (testing)"
VERSION_CODENAME=testing
ID=plasma
HOME_URL="https://plasmalinux.github.io/"
SUPPORT_URL="https://plasmalinux.github.io/"
BUG_REPORT_URL="https://plasmalinux.github.io/"

```

**Comment by rkarsnk** [comment]
下のに合わせておいてください．
```
PRETTY_NAME="PLDE Reimu 24.05"
NAME="PLDE"
VERSION_ID="24.05"
VERSION="24.05 Reimu"
VERSION_CODENAME=testing
ID=debian
HOME_URL="https://plasmalinux.github.io/"
SUPPORT_URL="https://plasmalinux.github.io/"
BUG_REPORT_URL="https://plasmalinux.github.io/"
```

**Comment by aruelu** [comment]
有難うございます。
修正してPR出します。
