### ISSUE TITLE
光学ドライブ周りの問題

### ISSUE THREAD

**Issue by Sylphid-Modder** [PlasmaLinux/PLDE_Livebuild#2]
/cdromの自動マウントがなされない。
及び、ファイルマネージャ(現段階ではThunar)への表示がなされない。

**Comment by rkarsnk** [comment]
以下のパッケージをインストールすることで問題が解消する．
- gvfs
- eject
- autofs

**Comment by rkarsnk** [comment]
TODO:
 PR作成する．

**Comment by rkarsnk** [comment]
@Sylphid-Modder 
PR #4 に対策書いてあるので試してみて．
