### ISSUE TITLE
PulseAudio

### ISSUE THREAD

**Issue by aruelu** [PlasmaLinux/PLDE_Livebuild#3]
「PulseAudioサーバーに接続されていません」
オーディオミキサーを開こうとすると、「コマンドpavucontrolの実行に失敗しました」と出る。
![image](https://user-images.githubusercontent.com/128954589/234738468-5c91c72f-c848-44da-b3b7-cc5833776db7.png)

![image](https://user-images.githubusercontent.com/128954589/234738361-f8d8f36a-124e-40c2-99e2-bd2c9201cb7e.png)

**Comment by rkarsnk** [comment]
@aruelu 
```
pulseaudio関係とpavucontrol関係のパッケージのインストールでいけました
```
インストールしたパッケージ名教えてください．

**Comment by aruelu** [comment]
sudo apt install pulseaudio
sudo apt install pavucontrol
でインストールしても結果は一緒だとは思います。

Synapticの履歴より

【pulseaudio関係】・・・pulseaudioをマークし依存関係を全てインストール
以下のパッケージがインストールされました:
apulse (0.1.13-2)
libasound2-plugins (1.2.7.1-1)
libavcodec59 (7:5.1.2-3)
libavutil57 (7:5.1.2-3)
libcodec2-1.0 (1.0.5-1)
libfftw3-single3 (3.3.10-1)
libgsm1 (1.0.22-1)
libhwy1 (1.0.3-3)
libjack-jackd2-0 (1.9.21~dfsg-2)
libjxl0.7 (0.7.0-10)
libmfx1 (22.5.4-1)
libpulsedsp (16.1+dfsg1-2+b1)
libsamplerate0 (0.2.2-3)
libshine3 (3.1.1-2)
libsnappy1v5 (1.1.9-3)
libsoxr0 (0.1.3-4)
libspeex1 (1.2.1-2)
libspeexdsp1 (1.2.1-1)
libswresample4 (7:5.1.2-3)
libtwolame0 (0.4.0-2)
libva-drm2 (2.17.0-1)
libva-x11-2 (2.17.0-1)
libva2 (2.17.0-1)
libvdpau1 (1.5-2)
libwebpmux3 (1.2.4-0.1)
libwebrtc-audio-processing1 (0.3-1+b1)
libwrap0 (7.6.q-32)
libx264-164 (2:0.164.3095+gitbaee400-2+b1)
libxvidcore4 (2:1.3.7-1)
libzvbi-common (0.2.41-1)
libzvbi0 (0.2.41-1)
ocl-icd-libopencl1 (2.3.1-1)
pulseaudio (16.1+dfsg1-2+b1)
pulseaudio-utils (16.1+dfsg1-2+b1)

【pavucontrol関係】・・・pavucontrolをマークし依存関係を全てインストール
以下のパッケージがインストールされました:
libatkmm-1.6-1v5 (2.28.3-1)
libcairomm-1.0-1v5 (1.14.4-2)
libcanberra-gtk3-0 (0.30-10)
libglibmm-2.4-1v5 (2.66.5-2)
libgtkmm-3.0-1v5 (3.24.7-1)
libjson-glib-1.0-0 (1.6.6-1)
libjson-glib-1.0-common (1.6.6-1)
libpangomm-1.4-1v5 (2.46.3-1)
libsigc++-2.0-0v5 (2.12.0-1)
pavucontrol (5.0-2)
